// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taqyzsisbtziouzgaujx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhcXl6c2lzYnR6aW91emdhdWp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2ODQ0NjIsImV4cCI6MjA3MzI2MDQ2Mn0.J3KwUwOu6p6fscAicUfqUmGkfeTEnBQpD6EFmLW9i88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});